#!/usr/bin/env python3
"""Local workbench init, validation and rendering. Python 3.10+, standard library only."""
from __future__ import annotations

import argparse
import copy
from datetime import datetime
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from urllib.parse import quote, unquote, urlsplit

ASSETS = Path(__file__).resolve().parent.parent / "assets"
MARKER = "<!-- Generated by ai-dev-workbench; edit workbench.json -->"
COLLECTIONS = ("requirements", "versions", "tasks", "gates", "evidence", "decisions", "archive")
STATES = {
    "requirements": {"idea", "ready", "scheduled", "accepted", "dropped"},
    "versions": {"candidate", "planned", "in_progress", "local_verified", "released", "archived"},
    "tasks": {"todo", "doing", "blocked", "done", "accepted"},
    "gates": {"pending", "passed", "failed", "waived"},
    "evidence": {"passed", "failed", "observed"},
}
FIELDS = {
    "requirements": ("id title problem scenario priority status source", "acceptance", "version_id"),
    "versions": ("id title goal status product_plan technical_plan execution_plan next_action", "scope non_goals requirements risks", ""),
    "tasks": ("id title version_id owner module status deliverable blocker next_action", "requirement_ids depends_on exit_criteria evidence_ids", ""),
    "gates": ("id version_id title kind status reason next_action", "evidence_ids", ""),
    "evidence": ("id version_id label kind status environment recorded_at command href summary", "", "task_id"),
    "decisions": ("id title decision rationale href", "", "version_id"),
    "archive": ("label href note", "", ""),
}

# S = text; L = string array; N = nullable ID; B = boolean. Nested declarations validate shape.
BLUEPRINT_SHAPE = {
    "positioning": "S", "users": [{"role": "S", "need": "S", "success": "S"}],
    "journey": [{"id": "S", "title": "S", "actor": "S", "action": "S", "object": "S", "output": "S", "module_ids": "L", "exception": "S"}],
    "modules": [{
        "id": "S", "name": "S", "positioning": "S", "value": "S", "users": "L", "stories": "L", "requirement_ids": "L",
        "pages": [{"id": "S", "name": "S", "purpose": "S", "interactions": "L", "states": "L", "route": "S", "priority": "S", "status": "S", "reality": "S", "task_ids": "L", "evidence_ids": "L"}],
        "technology": {"strategy": "S", "key_tech": "L", "mechanism": "S",
                       "objects": [{"name": "S", "states": "L", "truth": "S"}],
                       "apis": [{"method": "S", "path": "S", "purpose": "S"}],
                       "risks": [{"risk": "S", "mitigation": "S"}]},
    }],
    "architecture": {"summary": "S", "layers": [{"id": "S", "name": "S", "responsibility": "S", "module_ids": "L"}],
                     "edges": [{"from": "S", "to": "S", "label": "S"}],
                     "flows": [{"id": "S", "title": "S", "steps": [{"from": "S", "to": "S", "action": "S", "data": "S"}], "failure": "S"}]},
    "development": {"principles": [{"title": "S", "practice": "S"}],
                    "batches": [{"id": "S", "version_id": "S", "title": "S", "status": "S", "goal": "S", "why": "S", "task_ids": "L", "entry_conditions": "L", "exit_criteria": "L"}],
                    "verification": [{"level": "S", "method": "S", "evidence": "S"}], "sync_note": "S"},
    "evolution": [{"id": "S", "version_id": "S", "title": "S", "problem": "S", "before": "S", "after": "S", "rationale": "S", "impact": "S", "source": "S"}],
}

GOVERNANCE_SHAPE = {
    "design": {"principles": [{"title": "S", "rule": "S"}], "tokens": [{"name": "S", "value": "S", "purpose": "S"}],
               "components": [{"name": "S", "usage": "S", "states": "L"}], "ai_rules": "L", "checks": "L", "source": "S"},
    "stack": [{"id": "S", "area": "S", "choice": "S", "alternatives": "L", "why": "S", "tradeoffs": "L", "status": "S", "version_id": "N", "source": "S"}],
    "testing": {"strategy": "S", "levels": [{"name": "S", "scope": "S", "command": "S", "pass_criteria": "S", "evidence": "S"}],
                "critical_paths": [{"title": "S", "steps": "L", "expected": "S", "recovery": "S"}], "rules": "L", "source": "S"},
    "releases": [{"id": "S", "version_id": "S", "environment": "S", "state": "S", "artifact": "S", "recorded_at": "S",
                  "changes": "L", "preflight": "L", "deploy_steps": "L", "rollback": "S", "evidence_ids": "L", "notes": "S"}],
}


DISCOVERY_SHAPE = {
    "brief": {"raw_request": "S", "users": "S", "problem": "S", "scenario": "S", "outcome": "S",
              "success_metrics": "L", "constraints": "L", "non_goals": "L", "ai_role": "S", "baseline": "S", "source": "S"},
    "questions": [{"id": "S", "question": "S", "why": "S", "blocking": "B", "requirement_ids": "L", "version_id": "N",
                   "status": "S", "options": [{"id": "S", "label": "S", "description": "S"}], "selected_option_id": "N",
                   "answer": "S", "answer_source": "S", "answered_at": "S", "next_action": "S"}],
    "proposals": [{"id": "S", "title": "S", "question_ids": "L", "requirement_ids": "L", "version_id": "N", "blocking": "B",
                   "options": [{"id": "S", "title": "S", "summary": "S", "fit": "S", "scope": "L", "benefits": "L",
                                "tradeoffs": "L", "effort": "S", "risks": "L", "validation": "S"}],
                   "recommended_option_id": "N", "recommendation_reason": "S", "status": "S", "selected_option_id": "N",
                   "decision": "S", "decision_source": "S", "decided_at": "S"}],
    "assumptions": [{"id": "S", "statement": "S", "risk": "S", "validation": "S", "status": "S", "source": "S"}],
}


def shape_errors(value: object, schema: object, path: str) -> list[str]:
    errors = []
    if schema == "S":
        if not isinstance(value, str):
            errors.append(f"{path} 必须为字符串")
    elif schema == "B":
        if type(value) is not bool:
            errors.append(f"{path} 必须为布尔值")
    elif schema == "N":
        if value is not None and not (isinstance(value, str) and value.strip()):
            errors.append(f"{path} 必须为 ID 或 null")
    elif schema == "L":
        if not isinstance(value, list) or any(not isinstance(v, str) or not v.strip() for v in value):
            errors.append(f"{path} 必须为字符串列表")
    elif isinstance(schema, list):
        if not isinstance(value, list):
            errors.append(f"{path} 必须为列表")
        else:
            for index, child in enumerate(value):
                errors.extend(shape_errors(child, schema[0], f"{path}[{index}]"))
    elif isinstance(schema, dict):
        if not isinstance(value, dict):
            errors.append(f"{path} 必须为对象")
        else:
            for key, child in schema.items():
                if key not in value:
                    errors.append(f"{path}.{key} 缺少字段")
                else:
                    errors.extend(shape_errors(value[key], child, path + "." + key))
    return errors


def nested_ids(value: object) -> set[str]:
    if isinstance(value, dict):
        own = {value["id"]} if isinstance(value.get("id"), str) else set()
        return own.union(*(nested_ids(v) for v in value.values()))
    if isinstance(value, list):
        return set().union(*(nested_ids(v) for v in value))
    return set()


def validate_discovery(data: dict) -> list[str]:
    if "discovery" not in data:
        return []
    discovery = data["discovery"]
    errors = shape_errors(discovery, DISCOVERY_SHAPE, "discovery")
    if errors:
        return errors
    existing = nested_ids({key: value for key, value in data.items() if key != "discovery"})
    questions = {row["id"]: row for row in discovery["questions"]}
    requirements = {row["id"]: row for row in data["requirements"]}
    versions = {row["id"]: row for row in data["versions"]}
    archived = {vid for vid, version in versions.items() if version["status"] == "archived"}

    def require(ok: bool, message: str) -> None:
        if not ok:
            errors.append(message)

    def date(value: str, label: str) -> None:
        try:
            datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            errors.append(f"{label}: 日期必须为 ISO 8601")

    records = discovery["questions"] + discovery["proposals"] + discovery["assumptions"]
    records += [option for row in discovery["questions"] + discovery["proposals"] for option in row["options"]]
    for record in records:
        identifier = record["id"]
        require(bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", identifier)), f"澄清记录 ID 非法: {identifier}")
        require(identifier not in existing, f"澄清记录 ID 重复: {identifier}")
        existing.add(identifier)

    scoped = discovery["questions"] + discovery["proposals"]
    for row in scoped:
        rid, vid = row["id"], row["version_id"]
        require(vid is None or vid in versions, f"{rid}: 澄清关联版本不存在")
        for reqid in row["requirement_ids"]:
            req = requirements.get(reqid)
            require(req is not None, f"{rid}: 澄清需求 {reqid} 不存在")
            if req is not None and vid is not None:
                require(req["version_id"] in {None, vid}, f"{rid}: 需求 {reqid} 与澄清版本不一致")
        options = {option["id"] for option in row["options"]}
        selected = row["selected_option_id"]
        require(selected is None or selected in options, f"{rid}: selected_option_id 不属于本组选项")

    for question in discovery["questions"]:
        qid, state = question["id"], question["status"]
        require(state in {"open", "answered", "deferred"}, f"{qid}: 问题状态非法")
        if state == "answered":
            require(bool(question["answer"].strip()) and bool(question["answer_source"].strip()), f"{qid}: 已回答问题缺少回答或来源")
            date(question["answered_at"], qid + ".answered_at")
        else:
            require(question["selected_option_id"] is None and all(not question[field].strip() for field in ("answer", "answer_source", "answered_at")),
                    f"{qid}: 未回答问题不得预填选择或回答记录")
        if state == "deferred":
            require(bool(question["next_action"].strip()), f"{qid}: 暂缓问题缺少可执行下一步")

    for proposal in discovery["proposals"]:
        pid, state = proposal["id"], proposal["status"]
        require(state in {"proposed", "selected", "deferred", "superseded"}, f"{pid}: 方案状态非法")
        require(len(proposal["options"]) >= 2, f"{pid}: 方案比较至少需要两个选项")
        for qid in proposal["question_ids"]:
            require(qid in questions, f"{pid}: 关联问题 {qid} 不存在")
        recommended = proposal["recommended_option_id"]
        options = {option["id"] for option in proposal["options"]}
        require(recommended is None or recommended in options, f"{pid}: recommended_option_id 不属于本组选项")
        if recommended is not None:
            require(bool(proposal["recommendation_reason"].strip()), f"{pid}: 推荐方案缺少推荐理由")
        if state == "selected":
            require(bool(proposal["decision"].strip()) and bool(proposal["decision_source"].strip()), f"{pid}: 已选择方案缺少决策或来源")
            date(proposal["decided_at"], pid + ".decided_at")
        else:
            require(proposal["selected_option_id"] is None, f"{pid}: 未选择方案不得预填 selected_option_id")
            if state == "superseded":
                require(bool(proposal["decision"].strip()), f"{pid}: superseded 必须在 decision 说明替代情况")
                if proposal["decided_at"].strip():
                    date(proposal["decided_at"], pid + ".decided_at")
            else:
                require(all(not proposal[field].strip() for field in ("decision", "decision_source", "decided_at")),
                        f"{pid}: 未选择方案不得预填决策记录")

    for assumption in discovery["assumptions"]:
        aid, state = assumption["id"], assumption["status"]
        require(state in {"unverified", "validated", "rejected"}, f"{aid}: 假设状态非法")
        if state in {"validated", "rejected"}:
            require(bool(assumption["source"].strip()), f"{aid}: 已核查假设缺少来源")

    # Scope is explicit: requirement links take precedence over version or project scope.
    # Historical archived records remain a snapshot, even if a new project question is open.
    unresolved = [q for q in discovery["questions"] if q["blocking"] and q["status"] in {"open", "deferred"}]
    unresolved += [p for p in discovery["proposals"] if p["blocking"] and p["status"] in {"proposed", "deferred"}]
    for blocker in unresolved:
        bid, vid = blocker["id"], blocker["version_id"]
        linked = set(blocker["requirement_ids"])
        if linked:
            affected_requirements = linked
            affected_tasks = [task for task in data["tasks"] if linked.intersection(task["requirement_ids"])]
            affected_versions = {requirements[rid]["version_id"] for rid in linked if rid in requirements}
            if vid is not None:
                affected_versions.add(vid)
            forbidden_versions = {"local_verified", "released"}
        else:
            affected_requirements = {rid for rid, req in requirements.items() if vid is None or req["version_id"] == vid}
            affected_tasks = [task for task in data["tasks"] if vid is None or task["version_id"] == vid]
            affected_versions = set(versions) if vid is None else {vid}
            forbidden_versions = {"in_progress", "local_verified", "released"}
        for rid in affected_requirements:
            req = requirements.get(rid)
            if req is not None and req["version_id"] not in archived:
                require(req["status"] not in {"ready", "scheduled", "accepted"}, f"{bid}: 未决事项阻塞需求 {rid} 的 {req['status']} 状态")
        for task in affected_tasks:
            if task["version_id"] not in archived:
                require(task["status"] not in {"doing", "done", "accepted"}, f"{bid}: 未决事项阻塞任务 {task['id']} 的 {task['status']} 状态")
        for affected_vid in affected_versions:
            if affected_vid in versions and affected_vid not in archived:
                state = versions[affected_vid]["status"]
                require(state not in forbidden_versions, f"{bid}: 未决事项阻塞版本 {affected_vid} 的 {state} 状态")
    return errors


def validate_governance(data: dict) -> list[str]:
    if "governance" not in data:
        return []
    gov = data["governance"]
    errors = shape_errors(gov, GOVERNANCE_SHAPE, "governance")
    if errors:
        return errors
    existing = nested_ids({k: v for k, v in data.items() if k != "governance"})
    versions = {v["id"]: v for v in data["versions"]}
    evidence = {e["id"]: e for e in data["evidence"]}

    def require(ok: bool, message: str) -> None:
        if not ok:
            errors.append(message)

    for row in gov["stack"] + gov["releases"]:
        identifier = row["id"]
        require(bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", identifier)), f"治理记录 ID 非法: {identifier}")
        require(identifier not in existing, f"治理记录 ID 重复: {identifier}")
        existing.add(identifier)
    for choice in gov["stack"]:
        require(choice["status"] in {"proposed", "adopted", "retired"}, f"{choice['id']}: 选型状态非法")
        require(choice["version_id"] is None or choice["version_id"] in versions, f"{choice['id']}: 选型关联版本不存在")
        require(bool(choice["why"].strip()) and bool(choice["source"].strip()), f"{choice['id']}: 选型缺少理由或来源")
    for release in gov["releases"]:
        rid, vid, state = release["id"], release["version_id"], release["state"]
        require(vid in versions, f"{rid}: 发布版本不存在")
        require(state in {"planned", "candidate", "deployed", "verified", "rolled_back", "historical"}, f"{rid}: 发布记录状态非法")
        try:
            datetime.fromisoformat(release["recorded_at"].replace("Z", "+00:00"))
        except ValueError:
            errors.append(f"{rid}: 发布记录日期必须为 ISO 8601")
        passed = []
        for eid in release["evidence_ids"]:
            ev = evidence.get(eid)
            require(ev is not None, f"{rid}: 发布证据 {eid} 不存在")
            if ev:
                require(ev["version_id"] == vid, f"{rid}: 发布证据版本不匹配")
                passed.append(ev["version_id"] == vid and ev["status"] == "passed")
        if state in {"deployed", "verified", "rolled_back"}:
            require(any(passed), f"{rid}: 发布事实缺少匹配的 passed 证据")
        if state in {"deployed", "verified"}:
            require(any(g["version_id"] == vid and g["kind"] == "deploy" and g["status"] == "passed" for g in data["gates"]), f"{rid}: 发布缺少 deploy 通过记录")
        if state == "verified":
            require(vid in versions and versions[vid]["status"] == "released", f"{rid}: verified 发布必须关联已验收交付版本")
    return errors


def validate_blueprint(data: dict) -> list[str]:
    if "blueprint" not in data:
        return []
    errors = shape_errors(data["blueprint"], BLUEPRINT_SHAPE, "blueprint")
    if errors:
        return errors
    bp = data["blueprint"]
    all_ids = {r["id"] for name in COLLECTIONS if name != "archive" for r in data[name]}
    modules = {r["id"]: r for r in bp["modules"]}
    tasks = {r["id"]: r for r in data["tasks"]}
    reqs = {r["id"]: r for r in data["requirements"]}
    versions = {r["id"] for r in data["versions"]}
    evidence = {r["id"]: r for r in data["evidence"]}
    layers = {r["id"] for r in bp["architecture"]["layers"]}

    def require(ok: bool, message: str) -> None:
        if not ok:
            errors.append(message)

    objects = bp["journey"] + bp["modules"] + bp["architecture"]["layers"] + bp["architecture"]["flows"] + bp["development"]["batches"] + bp["evolution"]
    objects += [p for m in bp["modules"] for p in m["pages"]]
    for obj in objects:
        identifier = obj["id"]
        require(bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", identifier)), f"blueprint: 非法 ID {identifier}")
        require(identifier not in all_ids, f"blueprint: ID 重复 {identifier}")
        all_ids.add(identifier)
    for obj in bp["journey"] + bp["architecture"]["layers"]:
        for mid in obj["module_ids"]:
            require(mid in modules, f"{obj['id']}: 模块 {mid} 不存在")
    for edge in bp["architecture"]["edges"]:
        require(edge["from"] in layers and edge["to"] in layers, f"架构关系端点不存在: {edge['from']} → {edge['to']}")
    for module in bp["modules"]:
        for rid in module["requirement_ids"]:
            require(rid in reqs, f"{module['id']}: 需求 {rid} 不存在")
        for page in module["pages"]:
            pid = page["id"]
            require(page["priority"] in {"P0", "P1", "P2", "P3"}, f"{pid}: priority 非法")
            require(page["status"] in {"planned", "built", "verified"}, f"{pid}: 页面状态非法")
            require(page["reality"] in {"planned", "mock", "partial", "connected", "verified"}, f"{pid}: 真实度状态非法")
            for tid in page["task_ids"]:
                require(tid in tasks, f"{pid}: 任务 {tid} 不存在")
            applicable_versions = {tasks[tid]["version_id"] for tid in page["task_ids"] if tid in tasks}
            applicable_versions |= {reqs[rid]["version_id"] for rid in module["requirement_ids"] if rid in reqs}
            accepted_evidence = []
            for eid in page["evidence_ids"]:
                ev = evidence.get(eid)
                require(ev is not None, f"{pid}: 证据 {eid} 不存在")
                if ev:
                    match = ev["version_id"] in applicable_versions and (ev["task_id"] is None or ev["task_id"] in page["task_ids"])
                    require(match, f"{pid}: 证据 {eid} 与页面关联版本/任务不匹配")
                    accepted_evidence.append(match and ev["status"] == "passed")
            if page["status"] == "verified" or page["reality"] == "verified":
                require(any(accepted_evidence), f"{pid}: verified 缺少匹配的 passed 证据")
    for batch in bp["development"]["batches"]:
        require(batch["status"] in {"past", "current", "next", "later"}, f"{batch['id']}: 批次状态非法")
        require(batch["version_id"] in versions, f"{batch['id']}: 版本不存在")
        for tid in batch["task_ids"]:
            require(tid in tasks and tasks[tid]["version_id"] == batch["version_id"], f"{batch['id']}: 任务 {tid} 与批次版本不一致")
        require(bool(batch["why"].strip()) and bool(batch["exit_criteria"]), f"{batch['id']}: 缺少批次顺序依据/退出条件")
    for delta in bp["evolution"]:
        require(delta["version_id"] in versions, f"{delta['id']}: 演进版本不存在")
    return errors


def within(path: Path, root: Path) -> bool:
    return path.resolve().is_relative_to(root.resolve())


def local_href(href: str, root: Path) -> Path | None:
    if not href or any(ord(c) < 32 for c in href) or "\\" in href:
        raise ValueError("链接为空或包含控制字符/反斜线")
    parsed = urlsplit(href)
    if parsed.scheme in {"http", "https"} and parsed.netloc:
        return None
    if parsed.scheme or parsed.netloc or href.startswith("/"):
        raise ValueError("仅允许 http(s) 或仓库相对路径")
    if not parsed.path:
        raise ValueError("请提供文件路径，不使用孤立锚点")
    target = (root / unquote(parsed.path)).resolve()
    if not within(target, root):
        raise ValueError("路径超出项目根目录")
    return target


def validate(data: object, root: Path, check_links: bool = False) -> list[str]:
    errors: list[str] = []

    def need(condition: bool, message: str) -> None:
        if not condition:
            errors.append(message)

    def strings(obj: dict, names: str, label: str) -> None:
        for key in names.split():
            need(isinstance(obj.get(key), str), f"{label}.{key} 必须是字符串")

    def arrays(obj: dict, names: str, label: str) -> None:
        for key in names.split():
            val = obj.get(key)
            need(isinstance(val, list) and all(isinstance(x, str) and x.strip() for x in val), f"{label}.{key} 必须是非空字符串的列表（列表可为空）")

    def nullable(obj: dict, names: str, label: str) -> None:
        for key in names.split():
            need(key in obj and (obj[key] is None or isinstance(obj[key], str) and bool(obj[key].strip())), f"{label}.{key} 必须是 ID 或 null")

    if not isinstance(data, dict):
        return ["根数据必须为对象"]
    need(type(data.get("schema_version")) is int and data["schema_version"] == 1, "schema_version 必须为 1")
    project = data.get("project")
    if not isinstance(project, dict):
        return errors + ["project 必须为对象"]
    strings(project, "name purpose updated_at next_action", "project")
    nullable(project, "current_version online_version", "project")
    sources = project.get("sources")
    need(isinstance(sources, list), "project.sources 必须为列表")
    if isinstance(sources, list):
        for source in sources:
            if not isinstance(source, dict):
                errors.append("project.sources 每项必须为对象")
            else:
                strings(source, "label href", "source")
    for collection in COLLECTIONS:
        rows = data.get(collection)
        if not isinstance(rows, list):
            errors.append(f"{collection} 必须为列表")
            continue
        for row in rows:
            if not isinstance(row, dict):
                errors.append(f"{collection} 每项必须为对象")
                continue
            label = f"{collection}[{row.get('id', '?')}]"
            text_fields, list_fields, null_fields = FIELDS[collection]
            strings(row, text_fields, label)
            arrays(row, list_fields, label)
            nullable(row, null_fields, label)
            if collection == "gates":
                need(type(row.get("required")) is bool, f"{label}.required 必须为布尔值")
    if errors:
        return errors

    ids: set[str] = set()
    for collection in COLLECTIONS:
        for row in data[collection]:
            if collection == "archive":
                continue
            identifier = row["id"]
            need(bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", identifier)), f"非法 ID: {identifier}")
            need(identifier not in ids, f"ID 重复: {identifier}")
            ids.add(identifier)
            if collection in STATES:
                need(row["status"] in STATES[collection], f"{identifier}: 未知状态 {row['status']}")
    if errors:
        return errors

    versions = {x["id"]: x for x in data["versions"]}
    tasks = {x["id"]: x for x in data["tasks"]}
    requirements = {x["id"]: x for x in data["requirements"]}
    evidence = {x["id"]: x for x in data["evidence"]}

    for key in ("name", "purpose", "next_action"):
        need(bool(project[key].strip()), f"project.{key} 不得为空")
    for label, date in [("project.updated_at", project["updated_at"])] + [(x["id"], x["recorded_at"]) for x in evidence.values()]:
        try:
            datetime.fromisoformat(date.replace("Z", "+00:00"))
        except ValueError:
            errors.append(f"{label}: 日期必须为 ISO 8601")
    for key in ("current_version", "online_version"):
        need(project[key] is None or project[key] in versions, f"project.{key}: 版本不存在")
    if project["online_version"] in versions:
        need(versions[project["online_version"]]["status"] == "released", "online_version 必须指向已验证交付的版本")
    for collection in ("requirements", "tasks", "gates", "evidence", "decisions"):
        for row in data[collection]:
            vid = row["version_id"]
            need(vid is None or vid in versions, f"{row['id']}: version_id 不存在")
    for req in requirements.values():
        rid, vid = req["id"], req["version_id"]
        need(req["priority"] in {"P0", "P1", "P2", "P3"}, f"{rid}: priority 非法")
        if req["status"] in {"ready", "scheduled", "accepted"}:
            need(bool(req["acceptance"]), f"{rid}: 需求缺少验收条件")
        if req["status"] in {"scheduled", "accepted"}:
            need(vid in versions, f"{rid}: 排期/验收需求必须绑定版本")
        if vid in versions:
            need(rid in versions[vid]["requirements"], f"{rid}: 与版本 requirements 关联不一致")
        if req["status"] == "accepted":
            linked = [t for t in tasks.values() if rid in t["requirement_ids"]]
            need(bool(linked) and all(t["status"] == "accepted" for t in linked), f"{rid}: 关联任务尚未全部验收")
    for version in versions.values():
        for rid in version["requirements"]:
            need(rid in requirements and requirements[rid]["version_id"] == version["id"], f"{version['id']}: 需求 {rid} 未双向绑定")
        if version["status"] not in {"candidate", "archived"}:
            for field in ("goal", "product_plan", "technical_plan", "execution_plan", "scope"):
                need(bool(version[field]), f"{version['id']}: 缺少版本合同 {field}")
    for item in evidence.values():
        tid = item["task_id"]
        need(tid is None or tid in tasks and tasks[tid]["version_id"] == item["version_id"], f"{item['id']}: task_id 与版本不匹配")
        for field in ("label", "environment", "summary", "href"):
            need(bool(item[field].strip()), f"{item['id']}: 证据缺少 {field}")

    def check_evidence(row: dict, passed: bool, task: bool = False) -> None:
        matched = []
        for eid in row["evidence_ids"]:
            ev = evidence.get(eid)
            need(ev is not None, f"{row['id']}: 证据 {eid} 不存在")
            if ev:
                match = ev["version_id"] == row["version_id"] and (not task or ev["task_id"] in {None, row["id"]})
                need(match, f"{row['id']}: 证据 {eid} 属于其他版本/任务")
                matched.append(match and ev["status"] == "passed")
        if passed:
            need(any(matched), f"{row['id']}: 通过/验收状态缺少匹配的 passed 证据")

    for task in tasks.values():
        tid = task["id"]
        need(bool(task["deliverable"].strip()) and bool(task["exit_criteria"]), f"{tid}: 缺少产物或退出条件")
        for rid in task["requirement_ids"]:
            need(rid in requirements and requirements[rid]["version_id"] == task["version_id"], f"{tid}: 需求 {rid} 与任务版本不匹配")
        for dep in task["depends_on"]:
            need(dep in tasks, f"{tid}: 依赖 {dep} 不存在")
            if dep in tasks and task["status"] == "accepted":
                need(tasks[dep]["status"] in {"done", "accepted"}, f"{tid}: 依赖 {dep} 未完成")
        if task["status"] == "blocked":
            need(bool(task["blocker"].strip()) and bool(task["next_action"].strip()), f"{tid}: 阻塞缺少原因/下一步")
        check_evidence(task, task["status"] == "accepted", task=True)
    visited, active = set(), set()

    def visit(tid: str) -> None:
        if tid in active:
            errors.append(f"依赖成环: {tid}")
            return
        if tid in visited or tid not in tasks:
            return
        active.add(tid)
        for dep in tasks[tid]["depends_on"]:
            visit(dep)
        active.remove(tid)
        visited.add(tid)

    for tid in tasks:
        visit(tid)
    for gate in data["gates"]:
        need(gate["kind"] in {"local", "review", "backup", "deploy", "online", "other"}, f"{gate['id']}: kind 非法")
        if gate["status"] == "waived":
            need(bool(gate["reason"].strip()), f"{gate['id']}: 豁免必须有依据")
        check_evidence(gate, gate["status"] == "passed")
    for version in versions.values():
        vid = version["id"]
        gates = [g for g in data["gates"] if g["version_id"] == vid]
        if version["status"] == "local_verified":
            local = [g for g in gates if g["kind"] == "local" and g["required"]]
            need(bool(local) and all(g["status"] == "passed" for g in local), f"{vid}: 本地必需门未全部通过")
        if version["status"] == "released":
            vt = [t for t in tasks.values() if t["version_id"] == vid]
            need(bool(vt) and all(t["status"] == "accepted" for t in vt), f"{vid}: 发布版本任务未全部验收")
            need(all(g["status"] in {"passed", "waived"} for g in gates if g["required"]), f"{vid}: 发布仍有必需门未通过")
            for kind in ("deploy", "online"):
                need(any(g["kind"] == kind and g["status"] == "passed" for g in gates), f"{vid}: 缺少 {kind} 通过证据")
    link_rows = sources + data["evidence"] + data["decisions"] + data["archive"]
    for row in link_rows:
        try:
            target = local_href(row["href"], root)
            if target is not None and check_links:
                need(target.is_file(), f"本地链接文件不存在: {row['href']}")
        except ValueError as exc:
            errors.append(f"链接 {row['href']!r}: {exc}")
    errors.extend(validate_blueprint(data))
    errors.extend(validate_governance(data))
    errors.extend(validate_discovery(data))
    return errors


def empty_shape(schema: object) -> object:
    if isinstance(schema, dict):
        return {key: empty_shape(value) for key, value in schema.items()}
    if isinstance(schema, list) or schema == "L":
        return []
    if schema == "B":
        return False
    return None if schema == "N" else ""


def blank(name: str, purpose: str) -> dict:
    return {"schema_version": 1, "project": {
        "name": name, "purpose": purpose, "updated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "current_version": None, "online_version": None, "sources": [],
        "next_action": "核对已有需求与版本事实，录入首个可独立验收的迭代。",
    }, **{key: [] for key in COLLECTIONS}, "blueprint": empty_shape(BLUEPRINT_SHAPE), "governance": empty_shape(GOVERNANCE_SHAPE),
        "discovery": empty_shape(DISCOVERY_SHAPE)}


def browser_data(data: dict, root: Path, output: Path) -> dict:
    output = output.resolve()
    result = copy.deepcopy(data)
    result["_source_file"] = os.path.relpath(output / "workbench.json", root.resolve()).replace("\\", "/")
    for row in result["project"]["sources"] + result["evidence"] + result["decisions"] + result["archive"]:
        href = row["href"]
        row["_source_href"] = href
        target = local_href(href, root)
        if target is not None:
            parsed = urlsplit(href)
            row["href"] = quote(os.path.relpath(target, output).replace("\\", "/"), safe="/.")
            if parsed.query:
                row["href"] += "?" + parsed.query
            if parsed.fragment:
                row["href"] += "#" + parsed.fragment
    return result


def safe_json(data: object) -> str:
    return json.dumps(data, ensure_ascii=False).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def build(data: dict, root: Path, source: Path) -> list[Path]:
    errors = validate(data, root, check_links=True)
    if errors:
        raise ValueError("\n".join(errors))
    output = source.parent
    if source.name != "workbench.json":
        raise ValueError("源数据文件需命名为 workbench.json，保证页面源文件入口一致")
    template = (ASSETS / "workbench.html").read_text(encoding="utf-8")
    for token in ("__WORKBENCH_DATA__", "__PAGE_VERSION__", "__ROOT_PREFIX__"):
        if template.count(token) != 1:
            raise ValueError(f"模板占位符必须恰好一次: {token}")
    payload = safe_json(browser_data(data, root, output))
    pages = [(output / "index.html", None, "./")]
    pages += [(output / "versions" / (v["id"] + ".html"), v["id"], "../") for v in data["versions"]]
    # Preflight every destination before modifying any existing page.
    for path, _, _ in pages:
        if not within(path, root):
            raise ValueError(f"输出路径超出项目根目录: {path}")
        if path.exists() and MARKER not in path.read_text(encoding="utf-8")[:256]:
            raise ValueError(f"拒绝覆盖非本工具生成的页面: {path}")
    for path, vid, prefix in pages:
        values = {"__WORKBENCH_DATA__": payload, "__PAGE_VERSION__": safe_json(vid), "__ROOT_PREFIX__": safe_json(prefix)}
        html = MARKER + "\n" + re.sub(r"__WORKBENCH_DATA__|__PAGE_VERSION__|__ROOT_PREFIX__", lambda m: values[m[0]], template)
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
            handle.write(html)
            temporary = Path(handle.name)
        os.replace(temporary, path)
    return [p for p, _, _ in pages]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="action", required=True)
    for action in ("init", "validate", "build"):
        command = sub.add_parser(action)
        command.add_argument("--project-root", type=Path, required=True)
        if action == "init":
            command.add_argument("--directory", default="docs/workbench")
            command.add_argument("--name", required=True)
            command.add_argument("--purpose", required=True)
        else:
            command.add_argument("--data", type=Path, required=True)
        if action == "validate":
            command.add_argument("--check-links", action="store_true")
    args = parser.parse_args()
    root = args.project_root.resolve()
    try:
        if not root.is_dir():
            raise ValueError("项目根目录不存在")
        if args.action == "init":
            path = (root / args.directory / "workbench.json").resolve()
            if not within(path, root):
                raise ValueError("输出目录不得超出项目根目录")
            data = blank(args.name, args.purpose)
            errors = validate(data, root)
            if errors:
                raise ValueError("\n".join(errors))
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("x", encoding="utf-8") as handle:
                json.dump(data, handle, ensure_ascii=False, indent=2)
                handle.write("\n")
            print(f"已创建空白源文件: {path}")
        else:
            source = args.data.resolve()
            if not within(source, root):
                raise ValueError("源文件必须位于项目根目录内")
            data = json.loads(source.read_text(encoding="utf-8"))
            if args.action == "validate":
                errors = validate(data, root, args.check_links)
                if errors:
                    raise ValueError("\n".join(errors))
                print("校验通过：结构、引用、依赖和证据记录一致。未核验报告内容或远程服务。")
            else:
                paths = build(data, root, source)
                print(f"已生成 {len(paths)} 个页面: {paths[0]}")
        return 0
    except (OSError, ValueError, RecursionError) as exc:
        print(f"未完成：{exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
